#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  block compile pipenv install --two "$@"
  local pth_anchore="$(pipenv run which anchore-cli)"
  mkdir -p "$shome/bin"
  (set +f; cd bin && ln -nfs "$pth_anchore" anchore)
}

main "$@"
