#!/usr/bin/env bash

function _anchore_profile {
  local shome="${_anchore_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"

  export ANCHORE_CLI_USER=admin ANCHORE_CLI_PASS=foobar
}

_anchore_profile
