#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_anchore="$(anchore --version 2>/dev/null | awk '{print $NF}' || true)"
  jq -n --arg anchore "$ver_anchore" '{anchore: $anchore}'
}

version "$@"
